[kind_nodes]
kind-control-plane ansible_host=kind-control-plane br_ecmp_ip=fd00:ec00::1/64
kind-worker        ansible_host=kind-worker        br_ecmp_ip=fd00:ec00::2/64

[kind_nodes:vars]
ansible_connection=community.docker.docker
ansible_user=root
ansible_python_interpreter=auto_silent
