apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: br-ecmp-ipvlan
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "ipvlan",
          "master": "br-ecmp",
          "mode": "l2",
          "ipam": {
            "type": "static",
            "addresses": [
              {
                "address": "fd00:ec00::5/64",
                "gateway": "fd00:ec00::1"
              }
            ],
            "routes": [
              {"dst": "fd00:100::/32", "gw": "fd00:ec00::1"},
              {"dst": "fd00:100::/32", "gw": "fd00:ec00::2"}
            ]
          }
        },
        {
          "type": "route-override",
          "addroutes": [
            {"dst": "fd00:200::/64", "gw": "fd00:ec00::1"}
          ]
        }
      ]
    }
