apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-cp
  labels:
    app: nginx1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx1
  template:
    metadata:
      labels:
        app: nginx1
    spec:
      nodeSelector:
        kubernetes.io/hostname: cl1-control-plane
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"  
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"      
      containers:
      - name: ubuntu-container
        image: docker.io/library/simple-web1:latest
        imagePullPolicy: IfNotPresent

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-worker
  labels:
    app: nginx1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx1
  template:
    metadata:
      labels:
        app: nginx1
    spec:
      nodeSelector:
        kubernetes.io/hostname: cl1-worker
      containers:
      - name: ubuntu-container
        image: docker.io/library/simple-web1:latest
        imagePullPolicy: IfNotPresent

---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "blue-pool"
spec:
  blocks:
  - cidr: "172.21.0.0/24"
---

apiVersion: v1
kind: Service
metadata:
  name: nginx1-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx1

