---
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  disableDefaultCNI: true
  podSubnet: 10.1.0.0/16
  serviceSubnet: 172.20.1.0/24
nodes:
  - image: custom-kind-node:v1.29.0-network-tools
    role: control-plane
  - image: custom-kind-node:v1.29.0-network-tools
    role: worker