apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netshoot-daemonset
spec:
  selector:
    matchLabels:
      app: netshoot
  template:
    metadata:
      labels:
        app: netshoot
    spec:
      # コントロールプレーンノードも含める
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: netshoot
        image: nicolaka/netshoot:latest
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - "sleep infinity"
