cluster:
  name: bgp-cplane-dev-v4

image:
  override: "localhost:5000/cilium/cilium-dev:local"
  pullPolicy: Never
operator:
  image:
    override: "localhost:5000/cilium/operator-generic:local"
    pullPolicy: Never
    suffix: ""

routingMode: native

bgpControlPlane:
  enabled: true
  routerIDAllocation:
    mode: "ip-pool"
    ipPool: "1.1.1.0/24"

ipv4NativeRoutingCIDR: 10.0.0.0/8

ipam:
  mode: kubernetes

k8s:
  requireIPv4PodCIDR: true

debug:
  enabled: true
