apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot-deployment
  labels:
    app: netshoot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: netshoot
  template:
    metadata:
      labels:
        app: netshoot
    spec:
      containers:
      - name: netshoot
        image: nicolaka/netshoot:latest
        command: ["/bin/sh"]
        args: ["-c", "while true; do sleep 3600; done"]

---        

apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot-deployment-cp
  labels:
    app: netshoot-cp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netshoot-cp
  template:
    metadata:
      labels:
        app: netshoot-cp
    spec:
      nodeSelector:
        kubernetes.io/hostname: kind-control-plane
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: netshoot-cp
          image: nicolaka/netshoot:latest
          command: ["/bin/sh"]
          args: ["-c", "while true; do sleep 3600; done"]
