apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  ipFamily: dual
  disableDefaultCNI: true
  podSubnet: "10.100.0.0/16,fd00:10:255::/48"
nodes:
  - role: control-plane
    image: custom-kind-node:v1.29.0-network-tools
  - role: worker
    image: custom-kind-node:v1.29.0-network-tools