apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-netshoot-daemonset
  labels:
    app: nginx1
spec:
  selector:
    matchLabels:
      app: nginx1
  template:
    metadata:
      labels:
        app: nginx1
    spec:
      containers:
      - name: nginx1
        image: docker.io/library/my-netshoot-nginx:v2
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash", "-c", "iptables -A INPUT -p tcp --dport 55555 -j REJECT --reject-with icmp-port-unreachable; ip link set eth0 mtu 600 && exec nginx -g 'daemon off;'"]
        securityContext:
          privileged: true

---

apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "blue-pool"
spec:
  blocks:
  - cidr: "172.121.0.0/24"
---

apiVersion: v1
kind: Service
metadata:
  name: nginx1-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: tcp-test
      port: 55555
      targetPort: 55555
      protocol: TCP
    - name: udp-test
      port: 55555
      targetPort: 55555
      protocol: UDP
  selector:
    app: nginx1