apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPClusterConfig
metadata:
  name: control-plane
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: bgp-cplane-dev-v6-control-plane
  bgpInstances:
    - name: "instance-65001"
      localASN: 65001
      peers:
        - name: "peer-65000"
          peerAddress: fd00:10:0:1::1
          peerASN: 65000
          peerConfigRef:
            name: "cilium-peer"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPClusterConfig
metadata:
  name: worker
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: bgp-cplane-dev-v6-worker
  bgpInstances:
    - name: "instance-65002"
      localASN: 65002
      peers:
        - name: "peer-65000"
          peerAddress: fd00:10:0:2::1
          peerASN: 65000
          peerConfigRef:
            name: "cilium-peer"

---

apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer
spec:
  authSecretRef: bgp-auth-secret
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 15