cluster:
  name: bgp-cplane-dev-v6

image:
  override: "localhost:5000/cilium/cilium-dev:local"
  pullPolicy: Never
operator:
  image:
    override: "localhost:5000/cilium/operator-generic:local"
    pullPolicy: Never
    suffix: ""

routingMode: native

ipv4:
  enabled: false

ipv6:
  enabled: true

bgpControlPlane:
  enabled: true
  ipv6RouterIDAllocation:
    mode: mac-address

ipv6NativeRoutingCIDR: fd00::/16

ipam:
  mode: kubernetes

k8s:
  requireIPv6PodCIDR: true

debug:
  enabled: true
