# cilium-medium.yaml
cluster:
  name: kind-kind


bpf:
  masquerade: true
  monitorAggregation: none

k8sServiceHost: kind-control-plane
k8sServicePort: 6443
kubeProxyReplacement: true

ipv4:
  enabled: true
ipv6:
  enabled: false

debug:
  enabled: true
  verbose: datapath

ipam:
  mode: kubernetes

# Cilium Routing
routingMode: tunnel
tunnelProtocol: geneve

loadBalancer:
  algorithm: maglev
  dsrDispatch: geneve
  mode: dsr