apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-example
  namespace: monitoring
data:
  fluent-bit.conf: |
    [SERVICE]
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On
        Log_Level debug
        

    [INPUT]
        Name         dummy
        Tag          test.log
        Dummy        {"message":"Hello, Loki! This is a test log."}
        Rate         1 

    [OUTPUT]
        Name loki
        Match *
        Host loki.monitoring.svc.cluster.local
        Port 3100
        Labels {job="fluent-bit", instance="dummy"}
        Line_Format key_value
        Retry_Limit False
        Auto_Kubernetes_Labels Off

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: monitoring
  labels:
    k8s-app: fluent-bit
spec:
  selector:
    matchLabels:
      k8s-app: fluent-bit
  template:
    metadata:
      labels:
        k8s-app: fluent-bit
    spec:
      serviceAccountName: fluent-bit
      containers:
        - name: fluent-bit
          image: fluent/fluent-bit:2.0  # 必要に応じてバージョンを指定
          ports:
            - containerPort: 2020
              name: http
          volumeMounts:
            - name: config
              mountPath: /fluent-bit/etc/
            - name: varlog
              mountPath: /var/log
      volumes:
        - name: config
          configMap:
            name: fluent-bit-example
        - name: varlog
          hostPath:
            path: /var/log
            type: Directory

---

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit
rules:
  - apiGroups: [""]
    resources:
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit
subjects:
  - kind: ServiceAccount
    name: fluent-bit
    namespace: monitoring