apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  ipFamily: ipv6
  disableDefaultCNI: true
  podSubnet: "fd00:10:255::/48"
nodes:
  - role: control-plane
  - role: worker
  - role: worker