---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: control-plane
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: kind-control-plane
  bgpInstances:
  - name: ame: "instance-65001"
  - localASN: 65001
    neighbors:
    - peerAddress: "169.254.1.1/32"
      peerASN: 65000
      peerConfigRef:
        name: "cilium-peer"

---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: worker
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: kind-worker
  bgpInstances:
  - name: ame: "instance-65002"
  - localASN: 65002
    neighbors:
    - peerAddress: "169.254.2.1/32"
      peerASN: 65000
      peerConfigRef:
        name: "cilium-peer"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: worker2
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: kind-worker2
  bgpInstances:
  - name: ame: "instance-65003"
  - localASN: 65003
    neighbors:
    - peerAddress: "169.254.3.1/32"
      peerASN: 65000
      peerConfigRef:
        name: "cilium-peer"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: worker3
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: kind-worker3
  bgpInstances:
  - name: ame: "instance-65004"
  - localASN: 65004
    neighbors:
    - peerAddress: "169.254.4.1/32"
      peerASN: 65000
      peerConfigRef:
        name: "cilium-peer"
