apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netshoot-daemonset
spec:
  selector:
    matchLabels:
      app: netshoot
  template:
    metadata:
      labels:
        app: netshoot
    spec:
      # control-plane には conf を置かないのでワーカーのみ
      containers:
      - name: netshoot
        image: my-netshoot-nginx:v2
        imagePullPolicy: IfNotPresent
        command: ["nginx", "-g", "daemon off;"]
        securityContext:
          privileged: true
