[kind_nodes]
kind-control-plane ansible_host=kind-control-plane br_ecmp_ip=192.168.100.1/24
kind-worker        ansible_host=kind-worker        br_ecmp_ip=192.168.100.2/24

[kind_nodes:vars]
ansible_connection=community.docker.docker
ansible_user=root
ansible_python_interpreter=auto_silent
