# cilium-medium.yaml
cluster:
  name: kind-kind

k8sServiceHost: kind-control-plane
k8sServicePort: 6443
kubeProxyReplacement: true

ipv4:
  enabled: true
ipv6:
  enabled: false

encryption:
  enabled: true
  type: wireguard
  wireguard:
    persistentKeepalive: "20"
  
ipam:
  mode: kubernetes

# Cilium Routing
routingMode: native
ipv4NativeRoutingCIDR: 10.244.0.0/16
enableIPv4Masquerade: true
autoDirectNodeRoutes: true