# cilium-medium.yaml
cluster:
  name: kind-kind

image:
  repository: localhost:5000/cilium/cilium-dev
  tag: local
  useDigest: false

operator:
  image:
    repository: localhost:5000/cilium/operator
    tag: local
    useDigest: false
    suffix: ""

hubble:
  relay:
    image:
      repository: localhost:5000/cilium/hubble-relay
      tag: local
      useDigest: false

k8sServiceHost: kind-control-plane
k8sServicePort: 6443
kubeProxyReplacement: true

ipv4:
  enabled: true
ipv6:
  enabled: false

encryption:
  enabled: true
  type: wireguard
  wireguard:
    persistentKeepalive: "20"
  
ipam:
  mode: kubernetes

# Cilium Routing
routingMode: native
ipv4NativeRoutingCIDR: 10.100.0.0/16