apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPClusterConfig
metadata:
  name: control-plane
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: bgp-cplane-dev-v4-control-plane
  bgpInstances:
    - name: "instance-65001"
      localASN: 65001
      peers:
        - name: "peer-65000"
          peerAddress: 10.0.1.1
          peerASN: 65000
          peerConfigRef:
            name: "cilium-peer"
    - name: "instance-65001-second"
      localASN: 65001
      peers:
        - name: "peer-65002"
          peerAddress: 10.250.0.2
          peerASN: 65002
          peerConfigRef:
            name: "cilium-peer"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPClusterConfig
metadata:
  name: worker
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: bgp-cplane-dev-v4-worker
  bgpInstances:
    - name: "instance-65002"
      localASN: 65002
      peers:
        - name: "peer-65000"
          peerAddress: 10.0.2.1
          peerASN: 65000
          peerConfigRef:
            name: "cilium-peer"
    - name: "instance-65002-second"
      localASN: 65002
      peers:
        - name: "peer-65001"
          peerAddress: 10.250.0.1
          peerASN: 65001
          peerConfigRef:
            name: "cilium-peer"

---

apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer
spec:
  authSecretRef: bgp-auth-secret
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 15
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: "bgp"