apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: bgp-cplane-dev-v4
networking:
  disableDefaultCNI: true
  podSubnet: "10.1.0.0/16"
  serviceSubnet: "10.2.0.0/16"
nodes:
- image: custom-kind-node:v1.29.0-network-tools
  role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-ip: "10.0.1.1"
- image: custom-kind-node:v1.29.0-network-tools
  role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-ip: "10.0.1.2"
